MORTGAGE_QUESTIONS = [
    {
        "question_id": "credit_range",
        "label":       "What's your approximate credit score range?",
        "helper":      "A rough estimate is fine — this affects the rate range Gavvy shows you",
        "input_type":  "choice",
        "placeholder": None,
        "choices":     [
            "760+ (Excellent)",
            "720-759 (Good)",
            "660-719 (Fair)",
            "620-659 (Poor)",
            "Not sure",
        ],
    },
    {
        "question_id": "target_home_price",
        "label":       "What's the price range of homes you're looking at?",
        "helper":      "This helps Gavvy find the most relevant lenders and rates",
        "input_type":  "choice",
        "placeholder": None,
        "choices":     [
            "Under $250k",
            "$250k-$350k",
            "$350k-$500k",
            "$500k-$750k",
            "Over $750k",
        ],
    },
    {
        "question_id": "down_payment_amount",
        "label":       "How much are you putting down?",
        "helper":      "Exact amount is fine — we'll calculate the percentage",
        "input_type":  "currency",
        "placeholder": "85000",
        "choices":     None,
    },
    {
        "question_id": "has_existing_lender",
        "label":       "Have you already talked to a lender?",
        "helper":      "No pressure either way — helps Gavvy know where you are",
        "input_type":  "choice",
        "placeholder": None,
        "choices":     [
            "No, haven't started",
            "Yes, got a pre-qual letter",
            "Yes, have a full pre-approval",
            "Shopping multiple lenders now",
        ],
    },
    {
        "question_id": "loan_type_preference",
        "label":       "Do you have a loan type preference?",
        "helper":      "Gavvy will explain tradeoffs if you're unsure",
        "input_type":  "choice",
        "placeholder": None,
        "choices":     [
            "Conventional (20%+ down)",
            "FHA (lower down payment)",
            "VA (military/veteran)",
            "Not sure — help me decide",
        ],
    },
]